# -*- coding: utf-8 -*-
"""Assigment_02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pRgytbbJ0U_B-XVqCtwuOLJal4ONwmLD

1. Read yaml file and write into json file sample files are provided with the mail sample1.yaml
"""

import yaml
import json

with open("sample1.yaml", 'r') as Yaml_Input, open("sample1.json", "w") as JSON_Output:
      yamlObject = yaml.safe_load(Yaml_Input)
      json.dump(yamlObject, JSON_Output)
myjsonfile=open('sample1.json','r')
jsondata=myjsonfile.read()
obj=json.loads(jsondata)
print(type(obj))
print('The converted json file is' )
print(str(obj))

"""2. For the same above code write exception handing so that the code should handle wrong file and print it, sample2.yaml having wrong yaml format"""

#from google.colab import files
#uploaded = files.upload()
import yaml
import json
with open("sample2.yaml", 'r') as Yaml_Input, open("sample1.json", "w") as JSON_Output:
    try:
      yamlObject = yaml.safe_load(Yaml_Input)
      print(type(yamlObject))
      json.dump(yamlObject, JSON_Output)
    except:
        print("Error in yaml File")

"""create a base class on one file of folder 'a' file named 'shapes' and a method to find area, 
       create another file on another folder named 'b' and create 3 classes for rectangle, square and triangle
	   inheritting class shapes and those should contain methods to find circumstance and perimeter,
       find area, circumstance and perimeter of rectangle, square, triangle
"""

