# -*- coding: utf-8 -*-
"""Tic_tac_toe.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W7tCj5q7eqAtBnMOIq3yT71hyzkszTow

# **TIC TAC TOE**  Game
"""

def sum(a,b,c):
  """function to create sum function Because inbuilt sum function in python takes only two arguments"""
  return a+b+c
def printBoard(xState,zState):
  """Used to print the state of the board"""
  One_1 = 'X' if xState[0] else ('0' if zState[0] else 1 )
  Two_2 = 'X' if xState[1] else ('0' if zState[1] else 2 )
  Three_3 = 'X' if xState[2] else ('0' if zState[2] else 3 )
  Four_4 = 'X' if xState[3] else ('0' if zState[3] else 4 )
  five_5 = 'X' if xState[4] else ('0' if zState[4] else 5 )
  Six_6 = 'X' if xState[5] else ('0' if zState[5] else 6 )
  Siven_7 = 'X' if xState[6] else ('0' if zState[6] else 7 )
  Eight_8 = 'X' if xState[7] else ('0' if zState[7] else 8 )
  Nine_9 = 'X' if xState[8] else ('0' if zState[8] else 9 )
  print(f" {One_1} | {Two_2} | {Three_3} ")
  print(f"---|---|---")
  print(f" {Four_4} | {five_5} | {Six_6} ")
  print(f"---|---|---")
  print(f" {Siven_7} | {Eight_8} | {Nine_9} ")

def CheckWin(xState,zState):
  """This function will keep the track of win"""
  Wins=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]]
  for win in Wins:
    if (sum(xState[win[0]],xState[win[1]],xState[win[2]]) == 3):
      print("winner of this round is X")
      return 1
    if (sum(zState[win[0]],zState[win[1]],zState[win[2]]) == 3):
      print("winner of this round is O")
      return 0 
  return-1     


if __name__=="__main__":
  
  xState = [0,0,0,0,0,0,0,0,0]
  zState = [0,0,0,0,0,0,0,0,0]
  turn = 1 # Turn value will be One '1' if its the X turn and will Zero '0' when it be turn of O
  print('Welcome to Tic Tac Toe Game')#utility perpose
  while(True):
    printBoard(xState,zState)
    if(turn==1):
       print("Turn is of X's ")
       value=int(input("pleace enter the value: "))
       xState[value-1] = 1
    else:
       print("Turn is of O's ")
       value=int(input("pleace enter the value: "))
       #if(value==9)
       #zState[value-1] = 1 
       zState[value-1] = 1 
    cwin = CheckWin(xState,zState)
    if (cwin != -1):
        print("match got ended")
        break
    turn=1-turn #To change between X's and O'turn